### ISSUE TITLE
ChButton: добавить возможность кастомизировать ширину границ

### ISSUE THREAD

**Issue by raiymbekB** [chocofamilyme/choco-ui#117]
### Проблема

Сейчас при использовании класса .bordered для кнопки нельзя кастомизировать ширину границ, потому что она прописана в классе .ch-button (--ch-button-border-width: 1px). 

### Решение

Нужно убрать строку с инициализацией CSS переменной, задающей ширину границ. В классе .bordered на случай отсутствия переменной стоит fallback значение = 1px.

**Comment by KirIIISolovyov** [comment]
Исправлено в !127
